"""Run the README's sample requests (and the test IPs) against a deployment and save the results.

    uv run python scripts/sample_output.py https://<service-url> [--click-key KEY] [--out samples]

Writes samples/README.md (every request and response, with the served ad's text pulled out of the HTML),
samples/responses.json (raw responses) and one rendered .html per served ad, openable in a browser.
Uses only the public API (plus one /demo/serve call to show why the ranker picked an ad).
"""

import argparse
import json
import re
import time
from pathlib import Path
from typing import Any

import httpx2 as httpx

IPHONE = "Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148"
ANDROID = "Mozilla/5.0 (Linux; Android 15; Pixel 9) AppleWebKit/537.36 Mobile Safari/537.36"
README_CONTEXT = {
    "searchTerm": "space adventure",
    "tags": ["sci-fi", "rpg"],
    "category": "roleplay",
    "title": "Galaxy Companion",
    "nsfw": False,
}

SCENARIOS = [  # (slug, description, test IP, user agent, ppid, context)
    (
        "readme_request_us_iphone",
        "README sample request — US, iPhone",
        "214.78.0.1",
        IPHONE,
        "sample_user_1",
        README_CONTEXT,
    ),
    (
        "us_android",
        "US, Android (Galaxy Quest targets iOS only)",
        "214.78.0.1",
        ANDROID,
        "sample_user_2",
        README_CONTEXT,
    ),
    (
        "us_iphone_fantasy_chat",
        "US, iPhone, a fantasy chat",
        "214.78.0.1",
        IPHONE,
        "sample_user_3",
        {"searchTerm": "dragons", "tags": ["fantasy"], "category": "roleplay", "title": "Dragon Rider", "nsfw": False},
    ),
    (
        "gb_android",
        "GB, Android (only the inactive Kitchen campaign targets GB)",
        "2.125.160.217",
        ANDROID,
        "sample_user_4",
        README_CONTEXT,
    ),
    (
        "se_android",
        "SE, Android (only the inactive Kitchen campaign targets SE)",
        "89.160.20.113",
        ANDROID,
        "sample_user_8",
        README_CONTEXT,
    ),
    ("cn_iphone", "CN, iPhone (no campaign targets CN)", "175.16.199.1", IPHONE, "sample_user_5", README_CONTEXT),
    ("ph_iphone", "PH, iPhone (no campaign targets PH)", "202.196.224.1", IPHONE, "sample_user_9", README_CONTEXT),
    ("bt_android", "BT, Android (no campaign targets BT)", "67.43.156.1", ANDROID, "sample_user_10", README_CONTEXT),
    (
        "us_iphone_nsfw_chat",
        "US, iPhone, NSFW chat (campaigns are sfw-only by default)",
        "214.78.0.1",
        IPHONE,
        "sample_user_6",
        {**README_CONTEXT, "nsfw": True},
    ),
    (
        "us_desktop",
        "US, desktop browser (campaigns target iOS/Android)",
        "214.78.0.1",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_0) Safari/605.1.15",
        "sample_user_7",
        README_CONTEXT,
    ),
]


def field(html: str, name: str) -> str:
    match = re.search(rf'const {name}\s*=\s*"(.*?)";', html)
    return json.loads(f'"{match.group(1)}"') if match else ""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("base_url")
    parser.add_argument("--click-key", default="dev-click-key")
    parser.add_argument("--out", default="samples")
    parser.add_argument("--label", default="", help="where this ran, e.g. 'Cloud Run' (shown in the report)")
    args = parser.parse_args()
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    base = args.base_url.rstrip("/")
    c = httpx.Client(base_url=base, timeout=30)
    c.get("/health")  # wake the service if it scaled to zero
    ready = c.get("/ready").json()

    lines = [
        "# Sample output",
        "",
        f"Generated by `scripts/sample_output.py` against `{base}`{f' ({args.label})' if args.label else ''} "
        f"on {time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())}.",
        f"LLM: `{ready['llm']}` · CTR model: `{ready['ctr_model']['source']}` · Temporal: `{ready['temporal']}`.",
        "Country comes from the README's test IPs via `X-Forwarded-For`; OS from `User-Agent`. "
        "Each served ad's full HTML is saved next to this file (open it in a browser).",
        "",
    ]
    raw: dict[str, Any] = {"ready": ready}
    first_impression = None
    for slug, description, ip, ua, ppid, context in SCENARIOS:
        headers = {"X-Forwarded-For": ip, "User-Agent": ua}
        session = c.post("/session/create", json={"ppid": ppid}, headers=headers)
        body = {"position": 3, "session_id": session.json()["session_id"], "context": context}
        started = time.perf_counter()
        response = c.post("/load/native", json=body, headers=headers)
        elapsed = round(1000 * (time.perf_counter() - started))
        lines += [
            f"## {description}",
            "",
            "```http",
            f"POST /load/native   X-Forwarded-For: {ip}   User-Agent: {ua[:40]}…",
            json.dumps(body, ensure_ascii=False),
            "```",
            "",
        ]
        entry: dict[str, Any] = {"request": body, "status": response.status_code, "session_status": session.status_code}
        if response.status_code == 200:
            data = response.json()
            # The click key ships inside every ad by design, but keep it out of a public repo.
            html = data["rendered_html"].replace(args.click_key, "<click-api-key>")
            (out / f"{slug}.html").write_text(html)
            entry["response"] = {"impression_id": data["impression_id"], "rendered_html": f"see {slug}.html"}
            first_impression = first_impression or data["impression_id"]
            lines += [
                f"**200** in {elapsed} ms (round trip) · `impression_id`: `{data['impression_id']}` · [rendered ad]({slug}.html)",
                "",
                "| Field | Value |",
                "|---|---|",
                f"| Character | {field(html, 'CHAR_NAME')} |",
                f"| Author | @{field(html, 'CAMPAIGN')} |",
                f"| Message | {field(html, 'CHAR_MESSAGE')} |",
                f"| CTA | {field(html, 'CTA')} |",
                f"| Click-through | {field(html, 'TRACKING_URL')} |",
                "",
            ]
        else:
            entry["response"] = response.json() if response.content else None
            meaning = {204: "no fill: no eligible campaign", 404: "unknown session"}.get(response.status_code, "")
            lines += [f"**{response.status_code}** ({meaning})", ""]
        raw[slug] = entry

    # Why the ranker chose: the same pipeline via /demo/serve, which adds debug info
    demo = c.post(
        "/demo/serve", json={"ip": "214.78.0.1", "device": "ios", "ppid": "sample_explain", "context": README_CONTEXT}
    )
    if demo.status_code == 200 and demo.json().get("status") == 200:
        d = demo.json()["debug"]
        raw["ranking_explained"] = d
        lines += [
            "## Why that ad (README request, debug view via `/demo/serve`)",
            "",
            f"Picked `{d['campaign_id']}` ({d['ranking_reason']}); copy from `{d['copy_source']}`; {d['latency_ms']} ms server-side.",
            "",
            "| Campaign | p(click) V1 | LightGBM | FM | Score | Uncertainty |",
            "|---|---|---|---|---|---|",
        ]
        lines += [
            f"| {x['campaign_id']} | {x['p_v1']:.4f} | {x['p_lightgbm']:.4f} | {x['p_fm']:.4f} | {x['score']:.3f} | ±{x['uncertainty']:.3f} |"
            for x in d["candidates"]
        ]
        lines.append("")

    # Sessions and clicks
    s1 = c.post("/session/create", json={"ppid": "sample_session"}, headers={"X-Forwarded-For": "214.78.0.1"})
    s2 = c.post("/session/create", json={"ppid": "sample_session"}, headers={"X-Forwarded-For": "214.78.0.1"})
    lines += [
        "## Sessions",
        "",
        "| Call | Status | session_id |",
        "|---|---|---|",
        f"| first `POST /session/create` | {s1.status_code} | `{s1.json()['session_id']}` |",
        f"| again within 30 s | {s2.status_code} | `{s2.json()['session_id']}` |",
        "",
    ]
    unknown = c.post("/load/native", json={"position": 3, "session_id": "sess_unknown"}, headers={"User-Agent": IPHONE})
    lines += [f"`POST /load/native` with an unknown `session_id` → **{unknown.status_code}**", ""]
    if first_impression:
        auth = {"Authorization": f"Bearer {args.click_key}"}
        clicks = [
            c.post(f"/impressions/{first_impression}/click", headers=h).status_code
            for h in ({"Authorization": "Bearer wrong-key"}, auth, auth)
        ]
        lines += [
            "## Clicks (the ad's CTA calls this)",
            "",
            "| Call | Status |",
            "|---|---|",
            f"| wrong key | {clicks[0]} |",
            f"| first click | {clicks[1]} |",
            f"| repeat click (counted once) | {clicks[2]} |",
            "",
        ]
        raw["clicks"] = clicks

    (out / "README.md").write_text("\n".join(lines))
    (out / "responses.json").write_text(json.dumps(raw, indent=2, ensure_ascii=False))
    print(f"Wrote {out}/README.md, {out}/responses.json and {sum(1 for _ in out.glob('*.html'))} rendered ads")


if __name__ == "__main__":
    main()
