"""End-to-end check of a running deployment, exercising every capability with no fallbacks.

    uv run python scripts/smoke_test.py https://<service-url> [--click-key KEY] [--allow-fallback]

Creates a throwaway campaign that targets Bhutan (README test IP 67.43.156.1), so it is the only eligible
ad and the run is deterministic, then checks: dependencies (/ready), campaign + ad set CRUD with safe
retries, LLM copy pre-generated by Temporal, sessions, serving, rendering, clicks, and cleanup.
Exits non-zero on the first failure. --allow-fallback skips the "real LLM copy" requirement.
"""

import argparse
import sys
import time
import uuid
from typing import Any

import httpx2 as httpx

BT_IP = "67.43.156.1"
IPHONE = "Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148"
FALLBACK = ["Fallback line that real LLM copy should never match."]


def check(ok: bool, label: str, detail: Any = "") -> None:
    print(f"{'✓' if ok else '✗'} {label}" + (f"  {detail}" if detail != "" else ""))
    if not ok:
        sys.exit(1)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("base_url")
    parser.add_argument("--click-key", default="dev-click-key")
    parser.add_argument("--allow-fallback", action="store_true")
    parser.add_argument("--copy-timeout", type=float, default=300)
    args = parser.parse_args()
    run = uuid.uuid4().hex[:8]
    c = httpx.Client(base_url=args.base_url.rstrip("/"), timeout=30)

    # 1. Dependencies (the first request may wake the service from zero: allow for a cold start)
    check(c.get("/health").status_code == 200, "service is up")
    deadline = time.time() + 90
    while (ready := c.get("/ready").json())["temporal"] != "connected" and time.time() < deadline:
        time.sleep(3)
    check(ready["mongo"] == "ok" and ready["redis"] == "ok", "MongoDB and Redis reachable", f"{ready['mongo']}/{ready['redis']}")
    check(ready["temporal"] == "connected", "Temporal worker connected", ready["temporal"])
    check("golden_sample_max_diff" in ready["ctr_model"], "CTR model loaded and verified", ready["ctr_model"])
    llm_ok = isinstance(ready["llm"], dict)
    if llm_ok or not args.allow_fallback:
        check(llm_ok, "LLM configured (no fallback copy)", ready["llm"])
    else:
        print(f"- LLM not configured (--allow-fallback): {ready['llm']}")

    # 2. Campaign with a safe retry, then activate it
    campaign = {
        "campaign_name": f"Smoke Test {run} — Bhutan", "advertiser_company_id": "acmp_smoke",
        "geo_targets": ["BT"], "os_targets": ["ios", "android"],
        "ios_store_url": "https://apps.apple.com/app/id1", "android_store_url": "https://play.google.com/store/apps/details?id=smoke",
    }
    first = c.post("/campaigns", json=campaign, headers={"Idempotency-Key": f"camp-{run}"})
    retry = c.post("/campaigns", json=campaign, headers={"Idempotency-Key": f"camp-{run}"})
    check(first.status_code == 201, "POST /campaigns", first.json().get("campaign_id"))
    camp_id = first.json()["campaign_id"]
    check(retry.json()["campaign_id"] == camp_id, "retry with same Idempotency-Key returns the same campaign")
    check(c.patch(f"/campaigns/{camp_id}", json={"active": True}).json()["active"] is True, "PATCH activates it")

    try:
        # 3. Ad set: variants are the cartesian product; safe retry
        ad_set = {
            "campaign_id": camp_id, "ad_set_name": "Smoke heroes", "character_names": ["Luna", "Rex"],
            "video_urls": ["https://storage.googleapis.com/simula-public/assets/simula-campaigns/1781322499823-8.mp4"],
            "ctas": ["Play Free"], "ai_prompts": ["Excitedly tell a friend about tonight's dragon raid."],
            "fallback_copy": FALLBACK,
        }
        created = c.post("/adsets", json=ad_set, headers={"Idempotency-Key": f"adset-{run}"})
        check(created.status_code == 201 and len(created.json()["variants"]) == 2, "POST /adsets creates 2 x 1 x 1 x 1 = 2 variants")
        again = c.post("/adsets", json=ad_set, headers={"Idempotency-Key": f"adset-{run}"})
        check(again.json()["ad_set_id"] == created.json()["ad_set_id"], "retry returns the same ad set")

        # 4. Temporal pre-generates LLM copy for the new variants
        if llm_ok:
            deadline = time.time() + args.copy_timeout
            source = None
            while time.time() < deadline:
                demo = c.post("/demo/serve", json={"ip": BT_IP, "device": "ios", "ppid": f"smoke-copy-{run}-{int(time.time())}"})
                if demo.status_code == 404:
                    print("  (demo disabled: skipping the copy-source check)")
                    break
                source = demo.json().get("debug", {}).get("copy_source")
                if source == "pool":
                    break
                time.sleep(5)
            check(source in ("pool", None), "ad copy pre-generated by Temporal + LLM", f"copy_source={source}")

        # 5. Sessions
        s1 = c.post("/session/create", json={"ppid": f"smoke-{run}"}, headers={"X-Forwarded-For": BT_IP})
        s2 = c.post("/session/create", json={"ppid": f"smoke-{run}"}, headers={"X-Forwarded-For": BT_IP})
        check(s1.status_code == 201 and s2.status_code == 200, "session created, then reused while active")
        check(s1.json()["session_id"] == s2.json()["session_id"], "same session id")

        # 6. Serving
        served = c.post(
            "/load/native",
            json={"position": 3, "session_id": s1.json()["session_id"],
                  "context": {"searchTerm": "dragons", "tags": ["fantasy"], "category": "roleplay", "title": "Dragon Rider", "nsfw": False}},
            headers={"X-Forwarded-For": BT_IP, "User-Agent": IPHONE},
        )
        check(served.status_code == 200, "POST /load/native serves an ad", served.status_code)
        html = served.json()["rendered_html"]
        check(f"Smoke Test {run}" in html and "{{" not in html, "rendered template has the campaign and no placeholders")
        if llm_ok:
            check(FALLBACK[0] not in html, "character message is LLM copy, not fallback copy")
        nsfw = c.post("/load/native", json={"position": 3, "session_id": s1.json()["session_id"], "context": {"nsfw": True}},
                      headers={"X-Forwarded-For": BT_IP, "User-Agent": IPHONE})
        check(nsfw.status_code == 204, "brand safety: an sfw-only campaign doesn't serve in an nsfw chat")

        # 7. Clicks
        imp = served.json()["impression_id"]
        check(c.post(f"/impressions/{imp}/click", headers={"Authorization": "Bearer wrong"}).status_code == 401, "click with a wrong key -> 401")
        auth = {"Authorization": f"Bearer {args.click_key}"}
        check(c.post(f"/impressions/{imp}/click", headers=auth).status_code == 204, "click recorded")
        check(c.post(f"/impressions/{imp}/click", headers=auth).status_code == 204, "repeat click accepted (counted once)")
        check(any(x["campaign_id"] == camp_id for x in c.get("/campaigns?active=true").json()), "campaign listed from the cache")
    finally:
        # 8. Cleanup (cascades to the ad set and variants)
        check(c.delete(f"/campaigns/{camp_id}").status_code == 204, "cleanup: DELETE campaign")
    print("\nAll checks passed.")


if __name__ == "__main__":
    main()
